### ISSUE TITLE
que pasó con el repo?

### ISSUE THREAD

**Issue by lspigariol** [pdep-utn-frd/2019-tpwgame-xxxpdp_jfmxxx#1]
hay varios commits, pero no veo que hayan subido el tp. @Hayetj @Nepgy @mateoryser

**Comment by Hayetj** [comment]
Ya esta subido el trabajo Lucas, me había olvidado de mandarle el mensaje

**Comment by lspigariol** [comment]
falta el archivo .project, no se puede importar.
revisen la estructura de carpetas, no deberia haber una subcarpeta pacman, sino todo directamente en el raiz del repo

**Comment by Hayetj** [comment]
No lo puedo subir lucas, estoy haciendo team luego commit, paso las cosas
al staged changes y luego commit and push pero cuando entro al repositorio
no aparece

**Comment by lspigariol** [comment]
Primero de todo deberías hacer un pull.
Cuando agregues los archivos, fíjate que este el .project
Sí no, empeza de nuevo en un Repo limpio, aunque sea público, tan bien con
un proyecto nuevo copiandote los archivos fuente e imágenes. Y me pasas el
link.

**Comment by Hayetj** [comment]
Ahí ya lo subí como me dijiste lucas, se puede ver? y el tp de funcional ya lo habíamos subido, no se si lo pudo ver.

**Comment by lspigariol** [comment]
bien, ahí lo pude ver y probar.
mas alla que tomaron un juego ya hecho, vamos a hacer que las mofidicaciones que intentaron hacer funcionen.
les abro nuevos issues para cada correccion
